### PR TITLE
Using QSerialPort

### PR DESCRIPTION
**Pull request by fpoussin**
I've removed the old serial port code to use QSerialPort instead.

Tested with the simulator and it seems to work fine.

### CODE REVIEW

**Comment by malcom2073** [comment]
What OS did you test this on? I'd like to test it on actual hardware, I moved from QSerialPort to the other serialport library due to QSerialPort's use of async events internally even when using their non-async code causing odd behavior on OSX and Linux when using USB->Serial devices.

This can be tested by running the simulator on one computer, going out a USB->Serial cable, and then a usb->serial on a second computer. I can test this when I get back from travel in two weeks if you don't have the hardware to give this a shot. 

 I'll look over the code tonight and see if I see any glaring issues, otherwise if it works in hardware I can pull it in.

**Comment by fpoussin** [comment]
I've tested it on Win10, I can also test on Linux.
I have an F4 board for native tests as well.

**Comment by fpoussin** [comment]
Tested on Win10 and Ubuntu 18.04, with my F4 discovery board: it works.
Old serial code does not work for me on Linux.

Interrogation gets stuck in all cases, but I don't think this comes from the serial code.

image

**Comment by fpoussin** [comment]
Should be good to merge now :)

**Pull request closed without merging**
